import Foundation
import SwiftData

struct VocabularySeedPayload: Codable {
    let version: Int
    let words: [VocabularySeedRecord]
}

struct VocabularySeedRecord: Codable {
    let id: UUID?
    let germanWord: String
    let article: String?
    let englishTranslation: String
    let level: String
    let category: String
    let version: Int?
}

struct FullVocabularyImportResult {
    let inserted: Int
    let updated: Int
    let totalProcessed: Int
}

final class DataSeeder {
    private let context: ModelContext

    static let starterVocabulary: [VocabularySeedRecord] = [
        .init(
            id: nil,
            germanWord: "Apfel",
            article: "der",
            englishTranslation: "apple",
            level: "A1",
            category: "Noun",
            version: 1
        ),
        .init(
            id: nil,
            germanWord: "Buch",
            article: "das",
            englishTranslation: "book",
            level: "A1",
            category: "Noun",
            version: 1
        ),
        .init(
            id: nil,
            germanWord: "Bahnhof",
            article: "der",
            englishTranslation: "station",
            level: "A2",
            category: "Noun",
            version: 1
        ),
        .init(
            id: nil,
            germanWord: "lernen",
            article: nil,
            englishTranslation: "to learn",
            level: "B1",
            category: "Verb",
            version: 1
        ),
        .init(
            id: nil,
            germanWord: "Rechnung",
            article: "die",
            englishTranslation: "invoice",
            level: "B2",
            category: "Noun",
            version: 1
        ),
        .init(
            id: nil,
            germanWord: "vorzüglich",
            article: nil,
            englishTranslation: "excellent",
            level: "C1",
            category: "Adjective",
            version: 1
        ),
        .init(
            id: nil,
            germanWord: "Weltanschauung",
            article: "die",
            englishTranslation: "worldview",
            level: "C2",
            category: "Noun",
            version: 1
        )
    ]

    init(context: ModelContext) {
        self.context = context
    }

    /// Imports records for A1...C2 in level order.
    func importA1ToC2(records: [VocabularySeedRecord]) throws {
        for level in CEFRLevel.allCases.sorted() {
            try importLevel(level, from: records)
        }
    }

    func importLevel(_ level: CEFRLevel, from records: [VocabularySeedRecord]) throws {
        let code = level.rawValue
        let filtered = records.filter { $0.level == code }
        for record in filtered {
            let word = VocabularyWord(
                id: record.id ?? UUID(),
                germanWord: record.germanWord,
                article: record.article,
                englishTranslation: record.englishTranslation,
                level: record.level,
                category: record.category,
                version: record.version ?? 1
            )
            context.insert(word)
        }
        try context.save()
    }

    /// Seeds only when local store is empty.
    func seedIfNeeded(records: [VocabularySeedRecord]) throws {
        let descriptor = FetchDescriptor<VocabularyWord>()
        let existing = try context.fetchCount(descriptor)
        guard existing == 0 else { return }
        try importA1ToC2(records: records)
    }

    /// Decode external vocabulary payload from either:
    /// - `{"version":1,"words":[...]}`
    /// - `[{...}, {...}]`
    static func decodeRecords(from data: Data) throws -> [VocabularySeedRecord] {
        let decoder = JSONDecoder()
        if let wrapped = try? decoder.decode(VocabularySeedPayload.self, from: data) {
            return wrapped.words
        }
        return try decoder.decode([VocabularySeedRecord].self, from: data)
    }

    /// Convenience for `full_vocabulary.json` generated by `vocab_processor.py`.
    func seedIfNeeded(jsonFileURL: URL) throws {
        let data = try Data(contentsOf: jsonFileURL)
        let records = try Self.decodeRecords(from: data)
        try seedIfNeeded(records: records)
    }

    /// Background-safe bulk upsert from `full_vocabulary.json` with batched saves and progress callbacks.
    static func importFullVocabularyFromBundle(
        container: ModelContainer,
        batchSize: Int = 500,
        onProgress: (@MainActor (Double) -> Void)? = nil
    ) async throws -> FullVocabularyImportResult {
        try await Task.detached(priority: .utility) {
            let context = ModelContext(container)
            guard let url = Bundle.main.url(forResource: "full_vocabulary", withExtension: "json") else {
                return FullVocabularyImportResult(inserted: 0, updated: 0, totalProcessed: 0)
            }

            let data = try Data(contentsOf: url)
            let records = try decodeRecords(from: data)
            guard !records.isEmpty else {
                await onProgress?(1.0)
                return FullVocabularyImportResult(inserted: 0, updated: 0, totalProcessed: 0)
            }

            let existing = try context.fetch(FetchDescriptor<VocabularyWord>())
            var byID: [UUID: VocabularyWord] = [:]
            var byWordLevel: [String: VocabularyWord] = [:]
            byID.reserveCapacity(existing.count)
            byWordLevel.reserveCapacity(existing.count)
            for row in existing {
                byID[row.id] = row
                byWordLevel["\(row.germanWord)|\(row.level)"] = row
            }

            var inserted = 0
            var updated = 0

            for (index, record) in records.enumerated() {
                guard CEFRLevel.isValidLevelCode(record.level) else { continue }

                let key = "\(record.germanWord)|\(record.level)"
                let resolvedArticle = record.article?.trimmingCharacters(in: .whitespacesAndNewlines)
                let normalizedArticle: String? = {
                    guard let art = resolvedArticle, !art.isEmpty, art.lowercased() != "none" else { return nil }
                    return art.lowercased()
                }()
                let incomingVersion = record.version ?? 1

                let target: VocabularyWord?
                if let sourceID = record.id, let byIdMatch = byID[sourceID] {
                    target = byIdMatch
                } else {
                    target = byWordLevel[key]
                }

                if let existingWord = target {
                    existingWord.germanWord = record.germanWord
                    existingWord.article = normalizedArticle
                    existingWord.englishTranslation = record.englishTranslation
                    existingWord.level = record.level
                    existingWord.category = record.category
                    existingWord.version = max(existingWord.version, incomingVersion)
                    updated += 1
                } else {
                    let newID = record.id ?? UUID()
                    let word = VocabularyWord(
                        id: newID,
                        germanWord: record.germanWord,
                        article: normalizedArticle,
                        englishTranslation: record.englishTranslation,
                        level: record.level,
                        category: record.category,
                        isMastered: false,
                        version: incomingVersion
                    )
                    context.insert(word)
                    byID[newID] = word
                    byWordLevel[key] = word
                    inserted += 1
                }

                let processed = index + 1
                if processed % max(batchSize, 1) == 0 {
                    try context.save()
                }
                await onProgress?(Double(processed) / Double(records.count))
            }

            try context.save()
            await onProgress?(1.0)
            return FullVocabularyImportResult(inserted: inserted, updated: updated, totalProcessed: records.count)
        }.value
    }
}
